services:
    api:
        image: web-flask:0.1.0-dev
        container_name: web-flask-dev
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "5101:8080"
        environment:
            - DEBUG=false
            - TZ=Asia/Shanghai
            - DOCKER_CONTAINER=true
        volumes:
            - ./volumes/logs:/usr/src/app/logs
            - ./:/usr/src/app/
        restart: always
        depends_on:
            - mongo
    mongo:
        image: mongo:5.0
        container_name: ziyuan77-db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27018:27017
        volumes:
            - ./volumes/mongodb_data:/data/db
        networks:
            - ziyuan-network
    mongo-express:
        image: mongo-express
        container_name: ziyuan-db-express
        restart: always
        ports:
            - 8082:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
        depends_on:
            - mongo
        networks:
            - ziyuan-network
networks:
    navi-network:
        name: ziyuan-network
