# 添加国家和地区的中文映射
COUNTRY_MAP = {
    'China': '中国',
    'United States': '美国',
    'Japan': '日本',
    'South Korea': '韩国',
    'United Kingdom': '英国',
    'Germany': '德国',
    'France': '法国',
    'Russia': '俄罗斯',
    'Canada': '加拿大',
    'Australia': '澳大利亚',
    'Brazil': '巴西',
    'India': '印度',
    'Italy': '意大利',
    'Spain': '西班牙',
    'Netherlands': '荷兰',
    'Switzerland': '瑞士',
    'Sweden': '瑞典',
    'Norway': '挪威',
    'Denmark': '丹麦',
    'Finland': '芬兰',
    'Poland': '波兰',
    'Belgium': '比利时',
    'Austria': '奥地利',
    'New Zealand': '新西兰',
    'Singapore': '新加坡',
    'Malaysia': '马来西亚',
    'Thailand': '泰国',
    'Vietnam': '越南',
    'Indonesia': '印度尼西亚',
    'Philippines': '菲律宾',
    'Mexico': '墨西哥',
    'Argentina': '阿根廷',
    'Chile': '智利',
    'South Africa': '南非',
    'Egypt': '埃及',
    'Turkey': '土耳其',
    'Israel': '以色列',
    'Saudi Arabia': '沙特阿拉伯',
    'United Arab Emirates': '阿联酋',
    'Iran': '伊朗',
    'Pakistan': '巴基斯坦',
    'Bangladesh': '孟加拉国',
    'Portugal': '葡萄牙',
    'Greece': '希腊',
    'Ireland': '爱尔兰',
    'Ukraine': '乌克兰',
    'Czech Republic': '捷克',
    'Romania': '罗马尼亚',
    'Hungary': '匈牙利',
    'Slovakia': '斯洛伐克',
    'Croatia': '克罗地亚',
    'Slovenia': '斯洛文尼亚',
    'Bulgaria': '保加利亚',
    'Serbia': '塞尔维亚',
    'Morocco': '摩洛哥',
    'Nigeria': '尼日利亚',
    'Kenya': '肯尼亚',
    'Iraq': '伊拉克',
    'Afghanistan': '阿富汗',
    'Kazakhstan': '哈萨克斯坦',
    'Mongolia': '蒙古国'
}

# 中国省份映射
PROVINCE_MAP = {
    'Beijing': '北京市',
    'Shanghai': '上海市',
    'Tianjin': '天津市',
    'Chongqing': '重庆市',
    'Hebei': '河北省',
    'Shanxi': '山西省',
    'Liaoning': '辽宁省',
    'Jilin': '吉林省',
    'Heilongjiang': '黑龙江省',
    'Jiangsu': '江苏省',
    'Zhejiang': '浙江省',
    'Anhui': '安徽省',
    'Fujian': '福建省',
    'Jiangxi': '江西省',
    'Shandong': '山东省',
    'Henan': '河南省',
    'Hubei': '湖北省',
    'Hunan': '湖南省',
    'Guangdong': '广东省',
    'Hainan': '海南省',
    'Sichuan': '四川省',
    'Guizhou': '贵州省',
    'Yunnan': '云南省',
    'Shaanxi': '陕西省',
    'Gansu': '甘肃省',
    'Qinghai': '青海省',
    'Taiwan': '台湾省',
    'Inner Mongolia': '内蒙古自治区',
    'Guangxi': '广西壮族自治区',
    'Tibet': '西藏自治区',
    'Ningxia': '宁夏回族自治区',
    'Xinjiang': '新疆维吾尔自治区',
    'Hong Kong': '香港特别行政区',
    'Macau': '澳门特别行政区'
}

# 添加中国城市映射
CHINA_CITY_MAP = {
    'Beijing': {
        'Beijing': '北京市',
        'Dongcheng': '东城区',
        'Xicheng': '西城区',
        'Chaoyang': '朝阳区',
        'Haidian': '海淀区',
        'Fengtai': '丰台区',
        'Shijingshan': '石景山区',
        'Mentougou': '门头沟区',
        'Fangshan': '房山区',
        'Tongzhou': '通州区',
        'Shunyi': '顺义区',
        'Changping': '昌平区',
        'Daxing': '大兴区',
        'Huairou': '怀柔区',
        'Pinggu': '平谷区',
        'Miyun': '密云区',
        'Yanqing': '延庆区'
    },
    'Shanghai': {
        'Shanghai': '上海市',
        'Huangpu': '黄浦区',
        'Xuhui': '徐汇区',
        'Changning': '长宁区',
        'Jing\'an': '静安区',
        'Putuo': '普陀区',
        'Hongkou': '虹口区',
        'Yangpu': '杨浦区',
        'Minhang': '闵行区',
        'Baoshan': '宝山区',
        'Jiading': '嘉定区',
        'Pudong': '浦东新区',
        'Jinshan': '金山区',
        'Songjiang': '松江区',
        'Qingpu': '青浦区',
        'Fengxian': '奉贤区',
        'Chongming': '崇明区'
    },
    'Guangdong': {
        'Guangzhou': '广州市',
        'Shenzhen': '深圳市',
        'Zhuhai': '珠海市',
        'Shantou': '汕头市',
        'Foshan': '佛山市',
        'Shaoguan': '韶关市',
        'Dongguan': '东莞市',
        'Zhongshan': '中山市',
        'Jiangmen': '江门市',
        'Zhanjiang': '湛江市',
        'Maoming': '茂名市',
        'Zhaoqing': '肇庆市',
        'Huizhou': '惠州市',
        'Meizhou': '梅州市',
        'Shanwei': '汕尾市',
        'Heyuan': '河源市',
        'Yangjiang': '阳江市',
        'Qingyuan': '清远市',
        'Chaozhou': '潮州市',
        'Jieyang': '揭阳市',
        'Yunfu': '云浮市'
    },
    'Zhejiang': {
        'Hangzhou': '杭州市',
        'Ningbo': '宁波市',
        'Wenzhou': '温州市',
        'Jiaxing': '嘉兴市',
        'Huzhou': '湖州市',
        'Shaoxing': '绍兴市',
        'Jinhua': '金华市',
        'Quzhou': '衢州市',
        'Zhoushan': '舟山市',
        'Taizhou': '台州市',
        'Lishui': '丽水市'
    },
    'Jiangsu': {
        'Nanjing': '南京市',
        'Suzhou': '苏州市',
        'Wuxi': '无锡市',
        'Changzhou': '常州市',
        'Nantong': '南通市',
        'Xuzhou': '徐州市',
        'Yancheng': '盐城市',
        'Huaian': '淮安市',
        'Lianyungang': '连云港市',
        'Taizhou': '泰州市',
        'Suqian': '宿迁市',
        'Zhenjiang': '镇江市',
        'Yangzhou': '扬州市'
    },
    'Sichuan': {
        'Chengdu': '成都市',
        'Mianyang': '绵阳市',
        'Deyang': '德阳市',
        'Yibin': '宜宾市',
        'Panzhihua': '攀枝花市',
        'Leshan': '乐山市',
        'Nanchong': '南充市',
        'Suining': '遂宁市',
        'Guangan': '广安市',
        'Zigong': '自贡市',
        'Luzhou': '泸州市',
        'Neijiang': '内江市',
        'Ziyang': '资阳市',
        'Meishan': '眉山市',
        'Guangyuan': '广元市',
        'Dazhou': '达州市',
        'Bazhong': '巴中市',
        'Yaan': '雅安市',
        'Aba': '阿坝藏族羌族自治州',
        'Ganzi': '甘孜藏族自治州',
        'Liangshan': '凉山彝族自治州'
    },
    'Tianjin': {
        'Tianjin': '天津市',
        'Heping': '和平区',
        'Hedong': '河东区',
        'Hexi': '河西区',
        'Nankai': '南开区',
        'Hebei': '河北区',
        'Hongqiao': '红桥区',
        'Binhai': '滨海新区',
        'Dongli': '东丽区',
        'Xiqing': '西青区',
        'Jinnan': '津南区',
        'Beichen': '北辰区',
        'Wuqing': '武清区',
        'Baodi': '宝坻区',
        'Jinghai': '静海区',
        'Ninghe': '宁河区'
    },
    'Chongqing': {
        'Chongqing': '重庆市',
        'Yuzhong': '渝中区',
        'Dadukou': '大渡口区',
        'Jiangbei': '江北区',
        'Shapingba': '沙坪坝区',
        'Jiulongpo': '九龙坡区',
        'Nanan': '南岸区',
        'Beibei': '北碚区',
        'Yubei': '渝北区',
        'Banan': '巴南区',
        'Qianjiang': '黔江区',
        'Wanzhou': '万州区',
        'Fuling': '涪陵区',
        'Changshou': '长寿区',
        'Jiangjin': '江津区',
        'Hechuan': '合川区',
        'Yongchuan': '永川区',
        'Nanchuan': '南川区',
        'Bishan': '璧山区',
        'Tongliang': '铜梁区',
        'Tongnan': '潼南区',
        'Dazu': '大足区',
        'Rongchang': '荣昌区',
        'Liangping': '梁平区',
        'Wulong': '武隆区',
        'Zhongxian': '忠县',
        'Kaixian': '开县',
        'Yunyang': '云阳县',
        'Fengjie': '奉节县',
        'Wushan': '巫山县',
        'Wuxi': '巫溪县',
        'Shizhu': '石柱土家族自治县',
        'Xiushan': '秀山土家族苗族自治县',
        'Youyang': '酉阳土家族苗族自治县',
        'Pengshui': '彭水苗族土家族自治县'
    },
    'Hebei': {
        'Shijiazhuang': '石家庄市',
        'Tangshan': '唐山市',
        'Qinhuangdao': '秦皇岛市',
        'Handan': '邯郸市',
        'Xingtai': '邢台市',
        'Baoding': '保定市',
        'Zhangjiakou': '张家口市',
        'Chengde': '承德市',
        'Cangzhou': '沧州市',
        'Langfang': '廊坊市',
        'Hengshui': '衡水市'
    },
    'Shanxi': {
        'Taiyuan': '太原市',
        'Datong': '大同市',
        'Yangquan': '阳泉市',
        'Changzhi': '长治市',
        'Jincheng': '晋城市',
        'Shuozhou': '朔州市',
        'Jinzhong': '晋中市',
        'Yuncheng': '运城市',
        'Xinzhou': '忻州市',
        'Linfen': '临汾市',
        'Lvliang': '吕梁市'
    },
    'Inner Mongolia': {
        'Hohhot': '呼和浩特市',
        'Baotou': '包头市',
        'Wuhai': '乌海市',
        'Chifeng': '赤峰市',
        'Tongliao': '通辽市',
        'Ordos': '鄂尔多斯市',
        'Hulunbuir': '呼伦贝尔市',
        'Bayannur': '巴彦淖尔市',
        'Ulanqab': '乌兰察布市',
        'Xing\'an': '兴安盟',
        'Xilingol': '锡林郭勒盟',
        'Alxa': '阿拉善盟'
    },
    'Liaoning': {
        'Shenyang': '沈阳市',
        'Dalian': '大连市',
        'Anshan': '鞍山市',
        'Fushun': '抚顺市',
        'Benxi': '本溪市',
        'Dandong': '丹东市',
        'Jinzhou': '锦州市',
        'Yingkou': '营口市',
        'Fuxin': '阜新市',
        'Liaoyang': '辽阳市',
        'Panjin': '盘锦市',
        'Tieling': '铁岭市',
        'Chaoyang': '朝阳市',
        'Huludao': '葫芦岛市'
    },
    'Jilin': {
        'Changchun': '长春市',
        'Jilin': '吉林市',
        'Siping': '四平市',
        'Liaoyuan': '辽源市',
        'Tonghua': '通化市',
        'Baishan': '白山市',
        'Songyuan': '松原市',
        'Baicheng': '白城市',
        'Yanbian': '延边朝鲜族自治州'
    },
    'Heilongjiang': {
        'Harbin': '哈尔滨市',
        'Qiqihar': '齐齐哈尔市',
        'Jixi': '鸡西市',
        'Hegang': '鹤岗市',
        'Shuangyashan': '双鸭山市',
        'Daqing': '大庆市',
        'Yichun': '伊春市',
        'Jiamusi': '佳木斯市',
        'Qitaihe': '七台河市',
        'Mudanjiang': '牡丹江市',
        'Heihe': '黑河市',
        'Suihua': '绥化市',
        'Daxinganling': '大兴安岭地区'
    },
    'Anhui': {
        'Hefei': '合肥市',
        'Wuhu': '芜湖市',
        'Bengbu': '蚌埠市',
        'Huainan': '淮南市',
        'Maanshan': '马鞍山市',
        'Huaibei': '淮北市',
        'Tongling': '铜陵市',
        'Anqing': '安庆市',
        'Huangshan': '黄山市',
        'Chuzhou': '滁州市',
        'Fuyang': '阜阳市',
        'Suzhou': '宿州市',
        'Chaohu': '巢湖市',
        'Lu\'an': '六安市',
        'Bozhou': '亳州市',
        'Chizhou': '池州市',
        'Xuancheng': '宣城市'
    },
    'Fujian': {
        'Fuzhou': '福州市',
        'Xiamen': '厦门市',
        'Putian': '莆田市',
        'Sanming': '三明市',
        'Quanzhou': '泉州市',
        'Zhangzhou': '漳州市',
        'Nanping': '南平市',
        'Longyan': '龙岩市',
        'Ningde': '宁德市'
    },
    'Jiangxi': {
        'Nanchang': '南昌市',
        'Jingdezhen': '景德镇市',
        'Pingxiang': '萍乡市',
        'Jiujiang': '九江市',
        'Xinyu': '新余市',
        'Yingtan': '鹰潭市',
        'Ganzhou': '赣州市',
        'Ji\'an': '吉安市',
        'Yichun': '宜春市',
        'Fuzhou': '抚州市',
        'Shangrao': '上饶市'
    },
    'Shandong': {
        'Jinan': '济南市',
        'Qingdao': '青岛市',
        'Zibo': '淄博市',
        'Zaozhuang': '枣庄市',
        'Dongying': '东营市',
        'Yantai': '烟台市',
        'Weifang': '潍坊市',
        'Jining': '济宁市',
        'Taian': '泰安市',
        'Weihai': '威海市',
        'Rizhao': '日照市',
        'Laiwu': '莱芜市',
        'Linyi': '临沂市',
        'Dezhou': '德州市',
        'Liaocheng': '聊城市',
        'Binzhou': '滨州市',
        'Heze': '菏泽市'
    },
    'Henan': {
        'Zhengzhou': '郑州市',
        'Kaifeng': '开封市',
        'Luoyang': '洛阳市',
        'Pingdingshan': '平顶山市',
        'Anyang': '安阳市',
        'Hebi': '鹤壁市',
        'Xinxiang': '新乡市',
        'Jiaozuo': '焦作市',
        'Puyang': '濮阳市',
        'Xuchang': '许昌市',
        'Luohe': '漯河市',
        'Sanmenxia': '三门峡市',
        'Nanyang': '南阳市',
        'Shangqiu': '商丘市',
        'Xinyang': '信阳市',
        'Zhoukou': '周口市',
        'Zhumadian': '驻马店市',
        'Jiyuan': '济源市'
    },
    'Hubei': {
        'Wuhan': '武汉市',
        'Huangshi': '黄石市',
        'Shiyan': '十堰市',
        'Yichang': '宜昌市',
        'Xiangyang': '襄阳市',
        'Ezhou': '鄂州市',
        'Jingmen': '荆门市',
        'Xiaogan': '孝感市',
        'Jingzhou': '荆州市',
        'Huanggang': '黄冈市',
        'Xianning': '咸宁市',
        'Suizhou': '随州市',
        'Enshi': '恩施土家族苗族自治州',
        'Xiantao': '仙桃市',
        'Qianjiang': '潜江市',
        'Tianmen': '天门市',
        'Shennongjia': '神农架林区'
    },
    'Hunan': {
        'Changsha': '长沙市',
        'Zhuzhou': '株洲市',
        'Xiangtan': '湘潭市',
        'Hengyang': '衡阳市',
        'Shaoyang': '邵阳市',
        'Yueyang': '岳阳市',
        'Changde': '常德市',
        'Zhangjiajie': '张家界市',
        'Yiyang': '益阳市',
        'Chenzhou': '郴州市',
        'Yongzhou': '永州市',
        'Huaihua': '怀化市',
        'Loudi': '娄底市',
        'Xiangxi': '湘西土家族苗族自治州'
    },
    'Guangxi': {
        'Nanning': '南宁市',
        'Liuzhou': '柳州市',
        'Guilin': '桂林市',
        'Wuzhou': '梧州市',
        'Beihai': '北海市',
        'Fangchenggang': '防城港市',
        'Qinzhou': '钦州市',
        'Guigang': '贵港市',
        'Yulin': '玉林市',
        'Baise': '百色市',
        'Hezhou': '贺州市',
        'Hechi': '河池市',
        'Laibin': '来宾市',
        'Chongzuo': '崇左市'
    },
    'Hainan': {
        'Haikou': '海口市',
        'Sanya': '三亚市',
        'Sansha': '三沙市',
        'Danzhou': '儋州市',
        'Wuzhishan': '五指山市',
        'Qionghai': '琼海市',
        'Wenchang': '文昌市',
        'Wanning': '万宁市',
        'Dongfang': '东方市',
        'Ding\'an': '定安县',
        'Tunchang': '屯昌县',
        'Chengmai': '澄迈县',
        'Lingao': '临高县',
        'Baisha': '白沙黎族自治县',
        'Changjiang': '昌江黎族自治县',
        'Ledong': '乐东黎族自治县',
        'Lingshui': '陵水黎族自治县',
        'Baoting': '保亭黎族苗族自治县',
        'Qiongzhong': '琼中黎族苗族自治县'
    },
    'Guizhou': {
        'Guiyang': '贵阳市',
        'Liupanshui': '六盘水市',
        'Zunyi': '遵义市',
        'Anshun': '安顺市',
        'Bijie': '毕节市',
        'Tongren': '铜仁市',
        'Qianxinan': '黔西南布依族苗族自治州',
        'Qiandongnan': '黔东南苗族侗族自治州',
        'Qiannan': '黔南布依族苗族自治州'
    },
    'Yunnan': {
        'Kunming': '昆明市',
        'Qujing': '曲靖市',
        'Yuxi': '玉溪市',
        'Baoshan': '保山市',
        'Zhaotong': '昭通市',
        'Lijiang': '丽江市',
        'Pu\'er': '普洱市',
        'Lincang': '临沧市',
        'Chuxiong': '楚雄彝族自治州',
        'Honghe': '红河哈尼族彝族自治州',
        'Wenshan': '文山壮族苗族自治州',
        'Xishuangbanna': '西双版纳傣族自治州',
        'Dali': '大理白族自治州',
        'Dehong': '德宏傣族景颇族自治州',
        'Nujiang': '怒江傈僳族自治州',
        'Diqing': '迪庆藏族自治州'
    },
    'Tibet': {
        'Lhasa': '拉萨市',
        'Shigatse': '日喀则市',
        'Chamdo': '昌都市',
        'Nyingchi': '林芝市',
        'Shannan': '山南市',
        'Nagqu': '那曲市',
        'Ngari': '阿里地区'
    },
    'Shaanxi': {
        'Xi\'an': '西安市',
        'Tongchuan': '铜川市',
        'Baoji': '宝鸡市',
        'Xianyang': '咸阳市',
        'Weinan': '渭南市',
        'Yan\'an': '延安市',
        'Hanzhong': '汉中市',
        'Yulin': '榆林市',
        'Ankang': '安康市',
        'Shangluo': '商洛市'
    },
    'Gansu': {
        'Lanzhou': '兰州市',
        'Jiayuguan': '嘉峪关市',
        'Jinchang': '金昌市',
        'Baiyin': '白银市',
        'Tianshui': '天水市',
        'Wuwei': '武威市',
        'Zhangye': '张掖市',
        'Pingliang': '平凉市',
        'Jiuquan': '酒泉市',
        'Qingyang': '庆阳市',
        'Dingxi': '定西市',
        'Longnan': '陇南市',
        'Linxia': '临夏回族自治州',
        'Gannan': '甘南藏族自治州'
    },
    'Qinghai': {
        'Xining': '西宁市',
        'Haidong': '海东市',
        'Haibei': '海北藏族自治州',
        'Huangnan': '黄南藏族自治州',
        'Hainan': '海南藏族自治州',
        'Golog': '果洛藏族自治州',
        'Yushu': '玉树藏族自治州',
        'Haixi': '海西蒙古族藏族自治州'
    },
    'Ningxia': {
        'Yinchuan': '银川市',
        'Shizuishan': '石嘴山市',
        'Wuzhong': '吴忠市',
        'Guyuan': '固原市',
        'Zhongwei': '中卫市'
    },
    'Xinjiang': {
        'Urumqi': '乌鲁木齐市',
        'Karamay': '克拉玛依市',
        'Turpan': '吐鲁番市',
        'Hami': '哈密市',
        'Changji': '昌吉回族自治州',
        'Bortala': '博尔塔拉蒙古自治州',
        'Bayingol': '巴音郭楞蒙古自治州',
        'Aksu': '阿克苏地区',
        'Kizilsu': '克孜勒苏柯尔克孜自治州',
        'Kashgar': '喀什地区',
        'Hotan': '和田地区',
        'Ili': '伊犁哈萨克自治州',
        'Tacheng': '塔城地区',
        'Altay': '阿勒泰地区'
    },
    'Hong Kong': {
        'Central and Western': '中西区',
        'Wan Chai': '湾仔区',
        'Eastern': '东区',
        'Southern': '南区',
        'Yau Tsim Mong': '油尖旺区',
        'Sham Shui Po': '深水埗区',
        'Kowloon City': '九龙城区',
        'Wong Tai Sin': '黄大仙区',
        'Kwun Tong': '观塘区',
        'Kwai Tsing': '葵青区',
        'Tsuen Wan': '荃湾区',
        'Tuen Mun': '屯门区',
        'Yuen Long': '元朗区',
        'North': '北区',
        'Tai Po': '大埔区',
        'Sha Tin': '沙田区',
        'Sai Kung': '西贡区',
        'Islands': '离岛区'
    },
    'Macau': {
        'Nossa Senhora de Fatima': '花地玛堂区',
        'Santo Antonio': '花王堂区',
        'Sao Lazaro': '望德堂区',
        'Sao Lourenco': '风顺堂区',
        'Se': '大堂区',
        'Nossa Senhora do Carmo': '嘉模堂区',
        'Cotai': '路氹城',
        'Coloane': '路环'
    },
    'Taiwan': {
        'Taipei': '台北市',
        'New Taipei': '新北市',
        'Taoyuan': '桃园市',
        'Taichung': '台中市',
        'Tainan': '台南市',
        'Kaohsiung': '高雄市',
        'Keelung': '基隆市',
        'Hsinchu': '新竹市',
        'Chiayi': '嘉义市',
        'Hsinchu County': '新竹县',
        'Miaoli': '苗栗县',
        'Changhua': '彰化县',
        'Nantou': '南投县',
        'Yunlin': '云林县',
        'Chiayi County': '嘉义县',
        'Pingtung': '屏东县',
        'Yilan': '宜兰县',
        'Hualien': '花莲县',
        'Taitung': '台东县',
        'Penghu': '澎湖县',
        'Kinmen': '金门县',
        'Lienchiang': '连江县'
    }
}

import requests
from flask import request
import pytz
from datetime import datetime

def get_location_info(visitor_ip):
    """获取IP地理位置信息"""
    location = "未知"
    try:
        if visitor_ip == '127.0.0.1' or visitor_ip == 'localhost' or visitor_ip.startswith('192.168.') or visitor_ip.startswith('10.'):
            location = "本地网络"
        else:
            response = requests.get(f'http://ip-api.com/json/{visitor_ip}')
            if response.status_code == 200:
                data = response.json()
                if data['status'] == 'success':
                    country = COUNTRY_MAP.get(data['country'], data['country'])
                    if country == '中国':
                        province = PROVINCE_MAP.get(data['regionName'], data['regionName'])
                        city = CHINA_CITY_MAP.get(data['regionName'], {}).get(data['city'], data['city'])
                        location = f"{country} {province} {city}"
                    else:
                        region = PROVINCE_MAP.get(data['regionName'], data['regionName'])
                        city = data['city']
                        location = f"{country} {region} {city}"
    except Exception as e:
        print(f"Error getting location: {e}")
    
    return location

def get_visitor_ip():
    """获取访问者IP"""
    forwarded_for = request.headers.get('X-Forwarded-For')
    if forwarded_for:
        return forwarded_for.split(',')[0]
    return request.remote_addr

def get_current_time():
    """获取当前北京时间"""
    tz = pytz.timezone('Asia/Shanghai')
    return datetime.now(tz).strftime('%Y-%m-%d %H:%M:%S') 