name: Deploy to ECS

on:
    push:
        branches:
            - dev # 触发部署的分支

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.ECS_SSH_KEY }}

            - name: Deploy to ECS
              env:
                  ECS_HOST: ${{ secrets.ECS_HOST }}
                  ECS_USER: ${{ secrets.ECS_USER }}
              run: |
                  echo "Deploying application to ECS..."
                  ssh -o StrictHostKeyChecking=no $ECS_USER@$ECS_HOST "
                    ssh -p 2222 root@127.0.0.1 "cd /mnt/docker_hub/cicd && ./ziyuan77-web.sh"
                  "
